#!/bin/bash

# Script Purpose: To update all defind fields from Support Receiver or Business Partner to new naming
# Script Name: AbERP Demo Update
# Script Creater: Adam Sawtell
# Created: 11/09/2023
# Notes: 
# Outcomes: Changes all designated 
# - Changes all defined fields to new naming ad_field, name values to defind variable set in script.
# - Updates all defined fields to iscentrallymaintained = N

# AbilityERP Core Windows Updated
# - Support Reciever
# - Incident Report

# - Restarts AbilityERP (iDempiere ) Service


echo "flamingologic.com.au"

echo "***"
sleep 1
echo "**"
sleep 1
echo "*"

echo "Please enter client id - this is unique to the customers build:"
read var1

echo "Please enter envirnment IP address:"
read var2

echo "Please enter the naming you would like to use for all fields, this is the naming that will replace all Support Reciever and many Business Partner naming fields:"
read var3

echo "Ensure you have opened port 5432 in the enviroments security group to this IP, It is required to update Posgres Db"


echo "The values you entered are: $var1, $var2, $var3"

# Environment Variables
export ad_client_id=$var1
export environment_ip=$var2
export naming=$var3

echo "This script will update all defind data fields to new naming:"
echo "$var3"

# Update System Config Value

echo "Updating AbilityERP (iDempiere)"

sleep 3

echo "***"
sleep 1
echo "**"
sleep 1
echo "*"

PGUSER=adempiere
PGPASSWORD=flamingo
PGHOST=${environment_ip}
PGPORT=5432
PGDATABASE=idempiere

psql "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}" << EOF

UPDATE ad_window SET name = '$var3' WHERE ad_window_ID = 1000024;
UPDATE ad_window SET iscentrallymaintained = 'N' WHERE ad_window_ID = 1000024;

UPDATE ad_tab SET name = '$var3' WHERE ad_tab_ID = 1000027;
UPDATE ad_tab SET iscentrallymaintained = 'N' WHERE ad_tab_ID = 1000027;

UPDATE ad_menu SET name = '$var3' WHERE ad_menu_ID = 1000008;
UPDATE ad_menu SET iscentrallymaintained = 'N' WHERE ad_menu_ID = 1000008;

UPDATE ad_menu SET name = '$var3' WHERE ad_menu_ID = 1000034;
UPDATE ad_menu SET iscentrallymaintained = 'N' WHERE ad_menu_ID = 1000034;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000405;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000405;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000528;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000528;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000461;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000461;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000476;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000476;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000540;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000540;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1001474;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1001474;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1001514;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1001514;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1001042;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1001042;

UPDATE ad_field SET name = '$var3' WHERE ad_field_ID = 1000621;
UPDATE ad_field SET iscentrallymaintained = 'N' WHERE ad_field_ID = 1000621;


EOF

# Restarting AbilityERP (iDempiere) Service

echo "Updates to environment require a restart"

echo "***"
sleep 1
echo "**"
sleep 1
echo "*"

echo "Restarting AbilityERP (iDempiere) Service"

echo "Stopping AbilityERP (iDempiere) Service."

sudo service idempiere stop

if [ $? -eq 0 ]
then
  echo "AbilityERP (iDempeire) was successfully Stopped"
  date
else
  echo "Stop process failed"
fi

echo "Starting AbilityERP (iDempiere) Service - This may take 30 sec."

sleep 30

sudo service idempiere start

if [ $? -eq 0 ]
then
  echo "AbilityERP (iDempeire) was successfully Started"
  date
else
  echo "Start process failed"
fi

sleep 1

echo "Finished"

echo "*"

echo "Your environment is now available to test - Support Receiver naming has been updted to yur preferred language"

sleep 2

echo "flamingologic.com.au"

echo "*"

EOF
