#!/bin/bash

# Script Purpose: To create a test or dev enviroment from a Production enviroment
# Script Name: AbEERP Test Update
# Script Creater: Adam Sawtell
# Created: 25/03/2023
# Notes: 
# Outcomes:
# - Disable Sigles Sign On (SSO)
# - Update Use Email For Login to No
# - Update the Browser title
# - Update ZK Logo Small (Menu Page) Image
# - Update ZL Logo Large (Login Page)  Image


echo "flamingologic.com.au"

echo "***"
sleep 1
echo "**"
sleep 1
echo "*"


# Update System Config Value

ECHO

PGUSER=adempiere
PGPASSWORD=flamingo
PGHOST=3.27.10.3
PGPORT=5432
PGDATABASE=idempiere

psql "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}" << EOF

# Disable Single Sign On (SSO)
UPDATE ad_sysconfig WHERE ad_sysconfig_id = 200205 SET value = N

# Update Use Email For Login to No
UPDATE ad_sysconfig WHERE ad_sysconfig_id = 200214 SET value = N

# Update the ZK Browser title
UPDATE ad_sysconfig WHERE ad_sysconfig_id = 200003 SET value = AbERP TEST Site

# Update ZK Logo Small (Menu Page) Image
UPDATE ad_sysconfig WHERE ad_sysconfig_id = 1000001 SET value = https://fllogo.s3.us-east-2.amazonaws.com/test+Flamingo+Logic+1+pic.jpg

# Update ZL Logo Large (Login Page)  Image
UPDATE ad_sysconfig WHERE ad_sysconfig_id = 1000000 SET value = https://fllogo.s3.us-east-2.amazonaws.com/test+Flamingo+Logic+Small+pic.jpg

EOF
